version: "3.9"

services:
  fetch-metrics:
    build:
      context: .
      dockerfile: Dockerfile.fetch-metrics
    volumes:
      - metrics-data:/app/data
  rest-api:
    build:
      context: .
      dockerfile: Dockerfile.rest-api
    depends_on:
      - fetch-metrics
    environment:
      - DATABASE_URL=sqlite:////app/data/metrics.db
    ports:
      - "5000:5000"
    volumes:
      - metrics-data:/app/data

volumes:
  metrics-data:
