version: '3.9'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
  
  fetch:
    build: ./scripts
    volumes:
      - ./data:/app/data
    
  dashboard:
    build: ./dashboard
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data

