version: '3.9'

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
  
  fetch:
    build: ./scripts
    volumes:
      - ./data:/app/data
    environment:
      - REPO_NAME=pulsar
      - OWNER_NAME=Exein-io
    
  dashboard:
    build: ./dashboard
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data

